//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gOldCleaner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<ArrayOfFolderItemDto>
            <FolderItemDto>
              <Description>test</Description>
              <FolderName>C:\REPO\GDB\Utils\gOldCleaner\temp</FolderName>
              <DeleteAfter>-30</DeleteAfter>
            </FolderItemDto>
            <FolderItemDto>
              <Description>test</Description>
              <FolderName>C:\REPO\GDB\Utils\gOldCleaner\temp\1</FolderName>
              <DeleteAfter>-15</DeleteAfter>
            </FolderItemDto>
          </ArrayOfFolderItemDto>
")]
        public string FolderList {
            get {
                return ((string)(this["FolderList"]));
            }
        }
    }
}
